version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.0.0
    volumes:
      - /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - my_network
  cloudwatch-exporter-ec2:
    image: mizzy/technofy-cloudwatch-exporter:latest
    container_name: cloudwatch-exporter-ec2
    ports:
      - 9042:9042
    volumes:
      - /home/ubuntu/exporter_cloudwatch_ec2.yml:/etc/cloudwatch_exporter/config.yml
    networks:
      - my_network
  cloudwatch-exporter-elb:
    image: mizzy/technofy-cloudwatch-exporter:latest
    container_name: cloudwatch-exporter-elb
    ports:
      - 9043:9042
    volumes:
      - /home/ubuntu/exporter_cloudwatch_elb.yml:/etc/cloudwatch_exporter/config.yml
    networks:
      - my_network
  cloudwatch-exporter-ecs:
    image: mizzy/technofy-cloudwatch-exporter:latest
    container_name: cloudwatch-exporter-ecs
    ports:
      - 9044:9042
    volumes:
      - /home/ubuntu/exporter_cloudwatch_ecs.yml:/etc/cloudwatch_exporter/config.yml
    networks:
      - my_network
  cloudwatch-exporter-rds:
    image: mizzy/technofy-cloudwatch-exporter:latest
    container_name: cloudwatch-exporter-rds
    ports:
      - 9045:9042
    volumes:
      - /home/ubuntu/exporter_cloudwatch_rds.yml:/etc/cloudwatch_exporter/config.yml
    networks:
      - my_network
  cloudwatch-exporter-es:
    image: mizzy/technofy-cloudwatch-exporter:latest
    container_name: cloudwatch-exporter-es
    ports:
      - 9046:9042
    volumes:
      - /home/ubuntu/exporter_cloudwatch_es.yml:/etc/cloudwatch_exporter/config.yml
    networks:
      - my_network
  cloudwatch-exporter-system_linux:
    image: mizzy/technofy-cloudwatch-exporter:latest
    container_name: cloudwatch-exporter-system_linux
    ports:
      - 9048:9042
    volumes:
      - /home/ubuntu/exporter_cloudwatch_system_linux.yml:/etc/cloudwatch_exporter/config.yml
    networks:
      - my_network

 # grafana:
 #   container_name: grafana
 #   image: grafana/grafana:4.6.2
 #   ports:
 #     - 3000:3000
 #   networks:
 #     - my_network

networks:
  my_network:
    driver: bridge
