global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'prometheus:9090'
#  - job_name: 'cloudwatch-exporter'
#    static_configs:
#      - targets:
#        - 'cloudwatch-exporter:9106'
  - job_name: 'aws_billing'
    metrics_path: '/scrape'
    params:
      task: [billing]
      region: [us-east-1]
    static_configs:
      - targets:
          - 'cloudwatch-exporter-ec2:9042'
  - job_name: 'cloudwatch-exporter-ec2'
    metrics_path: '/scrape'
    params:
      task: [ec2]
    ec2_sd_configs:
      - region: ap-northeast-1
    relabel_configs:
      - source_labels: [__meta_ec2_instance_id]
        target_label: __param_target
      - target_label: __address__
        replacement: 'cloudwatch-exporter-ec2:9042'
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
  - job_name: 'cloudwatch-exporter-elb'
    metrics_path: '/scrape'
    params:
      task: [elb]
    static_configs:
      - targets:
          - 'cloudwatch-exporter-elb:9042'
  - job_name: 'cloudwatch-exporter-ecs'
    metrics_path: '/scrape'
    params:
      task: [ecs]
    static_configs:
      - targets:
          - 'cloudwatch-exporter-ecs:9042'
  - job_name: 'cloudwatch-exporter-rds'
    metrics_path: '/scrape'
    params:
      task: [rds]
    static_configs:
      - targets:
          - 'cloudwatch-exporter-rds:9042'
  - job_name: 'cloudwatch-exporter-es'
    metrics_path: '/scrape'
    params:
      task: [es]
    static_configs:
      - targets:
          - 'cloudwatch-exporter-es:9042'
