global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'prometheus:9090'
  - job_name: 'cloudwatch-exporter'
    static_configs:
      - targets:
        - 'cloudwatch-exporter:9106'
  - job_name: 'aws_billing'
    metrics_path: '/scrape'
    params:
      task: [billing]
      region: [us-east-1]
    static_configs:
      - targets: ['technofy-cloudwatch-exporter:9042']
  - job_name: 'ec2_cloudwatch'
    metrics_path: '/scrape'
    ec2_sd_configs:
      - region: ap-northeast-1
    relabel_configs:
      - source_labels: [job]
        target_label: __param_task
      - source_labels: [__meta_ec2_instance_id]
        target_label: __param_target
      - target_label: __address__
        replacement: 'technofy-cloudwatch-exporter:9042'
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
