global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
  - job_name: 'cloudwatch-exporter'
    static_configs:
      - targets:
        - 'cloudwatch-exporter-ec2:9106'
